FROM mcr.microsoft.com/windows/iotcore:1809

ARG EXE_DIR=bin/Debug/netcoreapp2.1/win-x64/publish

WORKDIR /app

COPY $EXE_DIR/ ./

CMD [ "SqueezeNetObjectDetectionNC.exe", "-mSqueezeNet.onnx", "-dLifeCam" ]